services:
  kong-database:
    image: postgres:11
    platform: linux/arm64
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    networks:
      - kong-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong:
    image: kong:3.5
    platform: linux/arm64
    user: "kong"
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_SSL: "off"
      KONG_ADMIN_SSL: "off"
      KONG_NGINX_USER: "kong kong"
      KONG_PROXY_SSL_VERIFY: "off"
      KONG_PROXY_SSL_VERIFY_DEPTH: "1"
      KONG_CLIENT_SSL: "off"
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      kong-database:
        condition: service_healthy
    networks:
      - kong-net

  orion:
    image: fiware/orion:3.10.1
    platform: linux/amd64
    ports:
      - "1026:1026"
    command: -dbhost mongo -logLevel INFO
    depends_on:
      - mongo
    networks:
      - kong-net

  mongo:
    image: mongo:4.4
    platform: linux/arm64
    command: mongod --nojournal
    networks:
      - kong-net

networks:
  kong-net:
  orion-net: