services:
  mongo:
    image: mongo:4.4
    command: mongod --nojournal
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ${NETWORK_NAME}