services:
  orion:
    image: fiware/orion:3.10.1
    platform: linux/amd64
    ports:
      - "1026:1026"
    command: -dbhost mongo -logLevel INFO
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1026/version"]
      interval: 5s
      retries: 5
    networks:
      - ${NETWORK_NAME}